/**
 * GENERATED by `far-country measure export` - DO NOT EDIT.
 *
 * The Ezekiel 45/48 holy-allotment measurement dataset (ADR 0017,
 * Track A): the holy district, priests'/Levites' portions, city
 * strip, and Ezekiel's city, text-native values with their
 * long-cubit realization. Meters happen at consumption via
 * LONG_CUBIT_M (ADR 0018). Every entry cites the ESV verse it
 * came from; tiers per docs/data-model.md.
 */

export interface AllotmentMeasurement {
  /** the number as the text gives it */
  value: number;
  unit: string;
  /** realization in long cubits (Ezek 40:5); null for counts */
  cu: number | null;
  ref: string;
  subject: string;
  tier: string;
}

export const EZA: Record<string, AllotmentMeasurement> = {
  'eza-city-portion-breadth': { value: 5000.0, unit: 'long-cubit', cu: 5000.0, ref: 'Ezekiel 45:6; Ezekiel 48:15', subject: 'the property of the city, breadth', tier: 'clear' },
  'eza-city-portion-length': { value: 25000.0, unit: 'long-cubit', cu: 25000.0, ref: 'Ezekiel 45:6; Ezekiel 48:15', subject: 'the property of the city, length', tier: 'clear' },
  'eza-city-remainder-east': { value: 10000.0, unit: 'long-cubit', cu: 10000.0, ref: 'Ezekiel 48:18', subject: 'remainder of the city strip alongside the holy portion, to the east', tier: 'clear' },
  'eza-city-remainder-west': { value: 10000.0, unit: 'long-cubit', cu: 10000.0, ref: 'Ezekiel 48:18', subject: 'remainder of the city strip alongside the holy portion, to the west', tier: 'clear' },
  'eza-city-circumference': { value: 18000.0, unit: 'long-cubit', cu: 18000.0, ref: 'Ezekiel 48:35', subject: 'the circumference of the city', tier: 'clear' },
  'eza-city-gates-per-side': { value: 3.0, unit: 'item', cu: null, ref: 'Ezekiel 48:30-34', subject: 'gates of the city on each side, named after the tribes of Israel', tier: 'clear' },
  'eza-city-open-land': { value: 250.0, unit: 'long-cubit', cu: 250.0, ref: 'Ezekiel 48:17', subject: 'open land around the city, on each side', tier: 'clear' },
  'eza-city-side': { value: 4500.0, unit: 'long-cubit', cu: 4500.0, ref: 'Ezekiel 48:16; Ezekiel 48:30; Ezekiel 48:32; Ezekiel 48:33; Ezekiel 48:34', subject: 'the city, each of its four sides', tier: 'clear' },
  'eza-sanctuary-open-space': { value: 50.0, unit: 'long-cubit', cu: 50.0, ref: 'Ezekiel 45:2', subject: 'open space around the sanctuary plot', tier: 'clear' },
  'eza-sanctuary-plot-side': { value: 500.0, unit: 'long-cubit', cu: 500.0, ref: 'Ezekiel 45:2', subject: 'square plot for the sanctuary within the holy district', tier: 'clear' },
  'eza-holy-district-breadth': { value: 20000.0, unit: 'long-cubit', cu: 20000.0, ref: 'Ezekiel 45:1; Ezekiel 48:9; Ezekiel 48:13', subject: 'the holy district set apart for the LORD, breadth', tier: 'debated' },
  'eza-holy-district-length': { value: 25000.0, unit: 'long-cubit', cu: 25000.0, ref: 'Ezekiel 45:1; Ezekiel 48:9; Ezekiel 48:13', subject: 'the holy district set apart for the LORD, length', tier: 'clear' },
  'eza-whole-portion-square': { value: 25000.0, unit: 'long-cubit', cu: 25000.0, ref: 'Ezekiel 48:8; Ezekiel 48:20', subject: 'the whole set-apart portion (holy district together with the property of the city), square', tier: 'clear' },
  'eza-levites-portion-breadth': { value: 10000.0, unit: 'long-cubit', cu: 10000.0, ref: 'Ezekiel 45:5; Ezekiel 48:13', subject: 'the Levites\' allotment, breadth', tier: 'clear' },
  'eza-levites-portion-length': { value: 25000.0, unit: 'long-cubit', cu: 25000.0, ref: 'Ezekiel 45:5; Ezekiel 48:13', subject: 'the Levites\' allotment, length', tier: 'clear' },
  'eza-priests-portion-breadth': { value: 10000.0, unit: 'long-cubit', cu: 10000.0, ref: 'Ezekiel 45:3; Ezekiel 48:10', subject: 'the priests\' allotment (the sanctuary section), breadth', tier: 'clear' },
  'eza-priests-portion-length': { value: 25000.0, unit: 'long-cubit', cu: 25000.0, ref: 'Ezekiel 45:3; Ezekiel 48:10', subject: 'the priests\' allotment (the sanctuary section), length', tier: 'clear' },
};
