/**
 * GENERATED by `far-country measure export` - DO NOT EDIT.
 *
 * The Revelation 21 city measurement dataset (ADR 0017): the
 * measuring-rod passage (Rev 21:15-17), text-native values only.
 * Revelation declares no internal unit standard, so meters happen
 * entirely in config.ts against the ESV footnote glosses
 * (ADR 0018 pattern). Every entry cites the ESV verse it came
 * from; tiers per docs/data-model.md.
 */

export interface CityMeasurement {
  /** the number as the text gives it */
  value: number;
  unit: string;
  ref: string;
  subject: string;
  tier: string;
}

export const REV: Record<string, CityMeasurement> = {
  'rev-city-side': { value: 12000.0, unit: 'stadia', ref: 'Revelation 21:16', subject: 'the city, each dimension (its length, width, and height are equal)', tier: 'clear' },
  'rev-city-wall': { value: 144.0, unit: 'cubit', ref: 'Revelation 21:17', subject: 'the wall of the city, measured by the angel', tier: 'fuzzy' },
};
