/**
 * GENERATED by `far-country measure export` - DO NOT EDIT.
 *
 * The Ezekiel temple measurement dataset (ADR 0017), text-native
 * values with their long-cubit realization. Meters happen in
 * templeModel.ts via LONG_CUBIT_M (ADR 0018). Every entry cites
 * the ESV verse it came from; tiers per docs/data-model.md.
 */

export interface TempleMeasurement {
  /** the number as the text gives it */
  value: number;
  unit: string;
  /** realization in long cubits (Ezek 40:5); null for counts */
  cu: number | null;
  ref: string;
  subject: string;
  tier: string;
}

export const EZT: Record<string, TempleMeasurement> = {
  'ezt-altar-base-breadth': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 43:13', subject: 'base of the altar, breadth', tier: 'clear' },
  'ezt-altar-base-height': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 43:13', subject: 'base of the altar', tier: 'clear' },
  'ezt-altar-base-rim': { value: 1.0, unit: 'span', cu: 0.43, ref: 'Ezekiel 43:13', subject: 'rim around the edge of the altar base', tier: 'clear' },
  'ezt-altar-hearth-height': { value: 4.0, unit: 'long-cubit', cu: 4.0, ref: 'Ezekiel 43:15', subject: 'the altar hearth', tier: 'clear' },
  'ezt-altar-hearth-side': { value: 12.0, unit: 'long-cubit', cu: 12.0, ref: 'Ezekiel 43:16', subject: 'the altar hearth, square', tier: 'clear' },
  'ezt-altar-horns': { value: 4.0, unit: 'item', cu: null, ref: 'Ezekiel 43:15', subject: 'horns projecting upward from the altar hearth', tier: 'clear' },
  'ezt-altar-ledge-rim': { value: 0.5, unit: 'long-cubit', cu: 0.5, ref: 'Ezekiel 43:17', subject: 'rim around the altar ledge', tier: 'clear' },
  'ezt-altar-ledge-side': { value: 14.0, unit: 'long-cubit', cu: 14.0, ref: 'Ezekiel 43:17', subject: 'the ledge of the altar, square', tier: 'clear' },
  'ezt-altar-lower-ledge-breadth': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 43:14', subject: 'breadth of the lower ledge', tier: 'clear' },
  'ezt-altar-lower-ledge-rise': { value: 2.0, unit: 'long-cubit', cu: 2.0, ref: 'Ezekiel 43:14', subject: 'from the base on the ground to the lower ledge', tier: 'clear' },
  'ezt-altar-surround-base': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 43:17', subject: 'the base of the altar, all around', tier: 'clear' },
  'ezt-altar-upper-ledge-breadth': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 43:14', subject: 'breadth at the larger ledge step', tier: 'clear' },
  'ezt-altar-upper-ledge-rise': { value: 4.0, unit: 'long-cubit', cu: 4.0, ref: 'Ezekiel 43:14', subject: 'from the smaller ledge to the larger ledge', tier: 'clear' },
  'ezt-chambers-gap': { value: 20.0, unit: 'long-cubit', cu: 20.0, ref: 'Ezekiel 41:10; Ezekiel 42:3', subject: 'between the side chambers of the temple and the other chambers, all around', tier: 'clear' },
  'ezt-chambers-outer-wall-length': { value: 50.0, unit: 'long-cubit', cu: 50.0, ref: 'Ezekiel 42:7; Ezekiel 42:8', subject: 'wall outside parallel to the chambers, toward the outer court, length', tier: 'clear' },
  'ezt-chambers-passage-length': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 42:4', subject: 'passage inward before the chambers, length', tier: 'fuzzy' },
  'ezt-chambers-passage-width': { value: 10.0, unit: 'long-cubit', cu: 10.0, ref: 'Ezekiel 42:4', subject: 'passage inward before the chambers, width', tier: 'clear' },
  'ezt-court-gate-to-gate': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 40:19; Ezekiel 40:23; Ezekiel 40:27', subject: 'from the inner front of the lower (outer) gate to the outer front of the inner court', tier: 'clear' },
  'ezt-free-space-breadth': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 41:11', subject: 'breadth of the free space around the house', tier: 'clear' },
  'ezt-gate-barrier': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 40:12', subject: 'barrier before the side rooms, on either side', tier: 'clear' },
  'ezt-gate-breadth': { value: 25.0, unit: 'long-cubit', cu: 25.0, ref: 'Ezekiel 40:13; Ezekiel 40:21; Ezekiel 40:25; Ezekiel 40:29; Ezekiel 40:33; Ezekiel 40:36', subject: 'breadth of the gate, from the ceiling of one side room to the ceiling of the other', tier: 'clear' },
  'ezt-gate-inner-threshold-depth': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:7', subject: 'threshold of the gate by the vestibule of the gate at the inner end', tier: 'clear' },
  'ezt-gate-jamb-thickness': { value: 2.0, unit: 'long-cubit', cu: 2.0, ref: 'Ezekiel 40:9', subject: 'jambs of the gate vestibule', tier: 'clear' },
  'ezt-gate-length': { value: 50.0, unit: 'long-cubit', cu: 50.0, ref: 'Ezekiel 40:15; Ezekiel 40:21; Ezekiel 40:25; Ezekiel 40:29; Ezekiel 40:33; Ezekiel 40:36', subject: 'from the front of the gate at the entrance to the front of the inner vestibule of the gate', tier: 'clear' },
  'ezt-gate-opening-length': { value: 13.0, unit: 'long-cubit', cu: 13.0, ref: 'Ezekiel 40:11', subject: 'length of the gateway (at the opening)', tier: 'fuzzy' },
  'ezt-gate-opening-width': { value: 10.0, unit: 'long-cubit', cu: 10.0, ref: 'Ezekiel 40:11', subject: 'width of the opening of the gateway', tier: 'clear' },
  'ezt-gate-sideroom-breadth': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:7', subject: 'side rooms of the gate, breadth', tier: 'clear' },
  'ezt-gate-sideroom-gap': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 40:7', subject: 'space between the side rooms', tier: 'clear' },
  'ezt-gate-sideroom-length': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:7', subject: 'side rooms of the gate, length', tier: 'clear' },
  'ezt-gate-sideroom-side': { value: 6.0, unit: 'long-cubit', cu: 6.0, ref: 'Ezekiel 40:12', subject: 'the side rooms, six cubits on either side', tier: 'clear' },
  'ezt-gate-siderooms-per-side': { value: 3.0, unit: 'item', cu: null, ref: 'Ezekiel 40:10; Ezekiel 40:21', subject: 'side rooms on either side of the gate', tier: 'clear' },
  'ezt-gate-threshold-depth': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:6', subject: 'threshold of the gate', tier: 'clear' },
  'ezt-gate-vestibule-depth': { value: 8.0, unit: 'long-cubit', cu: 8.0, ref: 'Ezekiel 40:9', subject: 'vestibule of the gateway', tier: 'clear' },
  'ezt-gate-vestibule-inside': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:8', subject: 'the vestibule of the gateway, measured on the inside', tier: 'fuzzy' },
  'ezt-gate-vestibule-sixty': { value: 60.0, unit: 'long-cubit', cu: 60.0, ref: 'Ezekiel 40:14', subject: '\'he measured also the vestibule, sixty cubits\'', tier: 'fuzzy' },
  'ezt-house-front-breadth': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 41:14', subject: 'breadth of the east front of the temple and the yard', tier: 'clear' },
  'ezt-house-gate-breadth': { value: 14.0, unit: 'long-cubit', cu: 14.0, ref: 'Ezekiel 40:48', subject: 'breadth of the gate of the temple vestibule', tier: 'fuzzy' },
  'ezt-house-gate-sidewall': { value: 3.0, unit: 'long-cubit', cu: 3.0, ref: 'Ezekiel 40:48', subject: 'sidewalls of the temple vestibule gate, on either side', tier: 'fuzzy' },
  'ezt-house-length': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 41:13', subject: 'the temple, length', tier: 'clear' },
  'ezt-house-platform-height': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 41:8', subject: 'raised platform all around the temple (the foundations of the side chambers)', tier: 'clear' },
  'ezt-house-steps': { value: 10.0, unit: 'step', cu: null, ref: 'Ezekiel 40:49', subject: 'steps up to the temple vestibule', tier: 'fuzzy' },
  'ezt-house-vestibule-breadth': { value: 12.0, unit: 'long-cubit', cu: 12.0, ref: 'Ezekiel 40:49', subject: 'breadth of the temple vestibule', tier: 'fuzzy' },
  'ezt-house-vestibule-jamb': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 40:48', subject: 'jambs of the vestibule of the temple, on either side', tier: 'clear' },
  'ezt-house-vestibule-length': { value: 20.0, unit: 'long-cubit', cu: 20.0, ref: 'Ezekiel 40:49', subject: 'length of the temple vestibule', tier: 'clear' },
  'ezt-house-vestibule-pillars': { value: 2.0, unit: 'item', cu: null, ref: 'Ezekiel 40:49', subject: 'pillars beside the jambs of the temple vestibule, one on either side', tier: 'clear' },
  'ezt-house-wall-thickness': { value: 6.0, unit: 'long-cubit', cu: 6.0, ref: 'Ezekiel 41:5', subject: 'wall of the temple', tier: 'clear' },
  'ezt-inner-court-chambers': { value: 2.0, unit: 'item', cu: null, ref: 'Ezekiel 40:44-46', subject: 'chambers in the inner court, at the sides of the north and south gates (for the priests)', tier: 'clear' },
  'ezt-inner-court-side': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 40:47', subject: 'the inner court, a square', tier: 'clear' },
  'ezt-inner-gate-steps': { value: 8.0, unit: 'step', cu: null, ref: 'Ezekiel 40:31; Ezekiel 40:34; Ezekiel 40:37', subject: 'steps up to the inner gates', tier: 'clear' },
  'ezt-inner-gate-vestibule-breadth': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 40:30', subject: 'vestibules all around (at the inner gates), breadth', tier: 'fuzzy' },
  'ezt-inner-gate-vestibule-length': { value: 25.0, unit: 'long-cubit', cu: 25.0, ref: 'Ezekiel 40:30', subject: 'vestibules all around (at the inner gates), length', tier: 'fuzzy' },
  'ezt-mhp-breadth': { value: 20.0, unit: 'long-cubit', cu: 20.0, ref: 'Ezekiel 41:4', subject: 'breadth of the Most Holy Place, across the nave', tier: 'clear' },
  'ezt-mhp-entrance-breadth': { value: 6.0, unit: 'long-cubit', cu: 6.0, ref: 'Ezekiel 41:3', subject: 'entrance of the inner room', tier: 'clear' },
  'ezt-mhp-entrance-jamb': { value: 2.0, unit: 'long-cubit', cu: 2.0, ref: 'Ezekiel 41:3', subject: 'jambs of the entrance to the inner room', tier: 'clear' },
  'ezt-mhp-entrance-sidewall': { value: 7.0, unit: 'long-cubit', cu: 7.0, ref: 'Ezekiel 41:3', subject: 'sidewalls of the inner-room entrance', tier: 'fuzzy' },
  'ezt-mhp-length': { value: 20.0, unit: 'long-cubit', cu: 20.0, ref: 'Ezekiel 41:4', subject: 'length of the Most Holy Place', tier: 'clear' },
  'ezt-nave-breadth': { value: 20.0, unit: 'long-cubit', cu: 20.0, ref: 'Ezekiel 41:2', subject: 'breadth of the nave', tier: 'clear' },
  'ezt-nave-entrance-breadth': { value: 10.0, unit: 'long-cubit', cu: 10.0, ref: 'Ezekiel 41:2', subject: 'entrance of the nave', tier: 'clear' },
  'ezt-nave-entrance-sidewall': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 41:2', subject: 'sidewalls of the nave entrance, on either side', tier: 'clear' },
  'ezt-nave-jamb-breadth': { value: 6.0, unit: 'long-cubit', cu: 6.0, ref: 'Ezekiel 41:1', subject: 'jambs of the nave, on each side', tier: 'clear' },
  'ezt-nave-length': { value: 40.0, unit: 'long-cubit', cu: 40.0, ref: 'Ezekiel 41:2', subject: 'length of the nave', tier: 'clear' },
  'ezt-outer-court-chambers': { value: 30.0, unit: 'item', cu: null, ref: 'Ezekiel 40:17', subject: 'chambers facing the pavement of the outer court', tier: 'clear' },
  'ezt-outer-gate-steps': { value: 7.0, unit: 'step', cu: null, ref: 'Ezekiel 40:22; Ezekiel 40:26', subject: 'steps up to the outer gates', tier: 'clear' },
  'ezt-outer-wall-height': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:5', subject: 'height of the wall around the outside of the temple area', tier: 'clear' },
  'ezt-outer-wall-thickness': { value: 1.0, unit: 'reed', cu: 6.0, ref: 'Ezekiel 40:5', subject: 'thickness of the wall around the outside of the temple area', tier: 'clear' },
  'ezt-precinct-side': { value: 500.0, unit: 'long-cubit', cu: 500.0, ref: 'Ezekiel 42:16-20', subject: 'the temple area measured on each of its four sides, with a wall all around, to make a separation between the holy and the common', tier: 'debated' },
  'ezt-priest-chambers-breadth': { value: 50.0, unit: 'long-cubit', cu: 50.0, ref: 'Ezekiel 42:2', subject: 'the north chamber block, breadth', tier: 'clear' },
  'ezt-priest-chambers-length': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 42:2; Ezekiel 42:8', subject: 'the north chamber block opposite the separate yard, length', tier: 'clear' },
  'ezt-priest-chambers-stories': { value: 3.0, unit: 'story', cu: null, ref: 'Ezekiel 42:3; Ezekiel 42:6', subject: 'the chamber blocks, stories', tier: 'clear' },
  'ezt-reed-length': { value: 6.0, unit: 'long-cubit', cu: 6.0, ref: 'Ezekiel 40:5', subject: 'the measuring reed in the man\'s hand', tier: 'clear' },
  'ezt-side-chamber-breadth': { value: 4.0, unit: 'long-cubit', cu: 4.0, ref: 'Ezekiel 41:5', subject: 'side chambers all around the temple', tier: 'clear' },
  'ezt-side-chamber-outer-wall': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 41:9', subject: 'thickness of the outer wall of the side chambers', tier: 'clear' },
  'ezt-side-chamber-stories': { value: 3.0, unit: 'story', cu: null, ref: 'Ezekiel 41:6', subject: 'side chambers, stories one over another', tier: 'clear' },
  'ezt-side-chambers-per-story': { value: 30.0, unit: 'item', cu: null, ref: 'Ezekiel 41:6', subject: 'side chambers in each story', tier: 'clear' },
  'ezt-slaughter-hooks-length': { value: 1.0, unit: 'handbreadth', cu: 0.142857, ref: 'Ezekiel 40:43', subject: 'hooks fastened all around within', tier: 'clear' },
  'ezt-slaughter-tables': { value: 8.0, unit: 'item', cu: null, ref: 'Ezekiel 40:41', subject: 'tables at the north gate on which to slaughter the offerings', tier: 'clear' },
  'ezt-stone-table-breadth': { value: 1.5, unit: 'long-cubit', cu: 1.5, ref: 'Ezekiel 40:42', subject: 'tables of hewn stone for the burnt offering, breadth', tier: 'clear' },
  'ezt-stone-table-height': { value: 1.0, unit: 'long-cubit', cu: 1.0, ref: 'Ezekiel 40:42', subject: 'tables of hewn stone for the burnt offering, height', tier: 'clear' },
  'ezt-stone-table-length': { value: 1.5, unit: 'long-cubit', cu: 1.5, ref: 'Ezekiel 40:42', subject: 'tables of hewn stone for the burnt offering, length', tier: 'clear' },
  'ezt-stone-tables-count': { value: 4.0, unit: 'item', cu: null, ref: 'Ezekiel 40:42', subject: 'tables of hewn stone for the burnt offering', tier: 'clear' },
  'ezt-west-building-breadth': { value: 70.0, unit: 'long-cubit', cu: 70.0, ref: 'Ezekiel 41:12', subject: 'building facing the separate yard on the west side, breadth', tier: 'clear' },
  'ezt-west-building-galleries-length': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 41:15', subject: 'length of the building facing the yard at the back with its galleries', tier: 'clear' },
  'ezt-west-building-length': { value: 90.0, unit: 'long-cubit', cu: 90.0, ref: 'Ezekiel 41:12', subject: 'building facing the separate yard on the west side, length', tier: 'clear' },
  'ezt-west-building-wall': { value: 5.0, unit: 'long-cubit', cu: 5.0, ref: 'Ezekiel 41:12', subject: 'wall of the western building, all around', tier: 'clear' },
  'ezt-wood-altar-breadth': { value: 2.0, unit: 'long-cubit', cu: 2.0, ref: 'Ezekiel 41:22', subject: 'the altar of wood, breadth', tier: 'fuzzy' },
  'ezt-wood-altar-height': { value: 3.0, unit: 'long-cubit', cu: 3.0, ref: 'Ezekiel 41:22', subject: 'the altar of wood (the table that is before the LORD), height', tier: 'clear' },
  'ezt-wood-altar-length': { value: 2.0, unit: 'long-cubit', cu: 2.0, ref: 'Ezekiel 41:22', subject: 'the altar of wood, length', tier: 'clear' },
  'ezt-yard-building-length': { value: 100.0, unit: 'long-cubit', cu: 100.0, ref: 'Ezekiel 41:13', subject: 'the yard and the building with its walls, length', tier: 'clear' },
};
