"""SQLite canonical store: ORM models, raw-SQL migrations, and engine helpers."""

from far_country.store.db import (
    DEFAULT_DB_PATH,
    create_engine_for_path,
    create_session_factory,
    init_db,
)
from far_country.store.models import (
    Base,
    Citation,
    Descriptor,
    Entity,
    EntityRelation,
    ExtractionRun,
    Verification,
)
from far_country.store.repo import (
    CountsByStatus,
    CountsByTier,
    DescriptorNotFoundError,
    DescriptorWithContext,
    RunSummary,
    counts_by_status,
    counts_by_tier,
    edit_descriptor,
    get_descriptor,
    list_approved_for_entity,
    list_descriptors,
    recent_runs,
    save_verification_results,
    update_review_status,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "Base",
    "Citation",
    "CountsByStatus",
    "CountsByTier",
    "Descriptor",
    "DescriptorNotFoundError",
    "DescriptorWithContext",
    "Entity",
    "EntityRelation",
    "ExtractionRun",
    "Verification",
    "RunSummary",
    "counts_by_status",
    "counts_by_tier",
    "create_engine_for_path",
    "create_session_factory",
    "edit_descriptor",
    "get_descriptor",
    "init_db",
    "list_approved_for_entity",
    "list_descriptors",
    "recent_runs",
    "save_verification_results",
    "update_review_status",
]
