"""The Ezekiel 40-43 temple measurement dataset (ADR 0017 proof of concept).

Hand-authored against the ESV text of Ezekiel 40-42 and 43:13-17 (fetched
from the ESV API; the text itself is never stored — ADR 0006). Values are
TEXT-NATIVE: the number and unit as the ESV prints them. Where the ESV
follows the Septuagint against the Hebrew (40:48-49; 41:22; 42:4) or where
the reading is a genuine translation-level dispute (42:16-20 cubits vs
reeds), the record is tiered `fuzzy`/`debated` with the variant documented
in its notes — the render follows the ESV as printed (RENDERING-DECISIONS
entry #7, ADR 0009 rule 4).

Unless a record says otherwise, "cubit" in Ezekiel 40-48 is the LONG cubit
the vision itself defines: "a cubit and a handbreadth" (Ezek 40:5; so also
43:13) — hence unit `long-cubit` throughout.

Record shape: (id, subject, dimension, value, unit, tier, cites, basis, notes)
  cites: list of (chapter, verse_start, verse_end | None); book is Ezekiel.
"""

from __future__ import annotations

TEMPLE_ENTITY = {
    "id": "ezekiel-temple",
    "name": "Ezekiel's Temple",
    "entity_type": "place",
    "summary": (
        "The measured temple complex of Ezekiel's vision (Ezek 40-48) - under "
        "the project's framing (ADR 0012) a literal future millennial sanctuary "
        "in restored Israel, distinct from and adjacent to the New Jerusalem "
        "(Rev 21:22; Ezek 48:10)."
    ),
}

Cite = tuple[int, int, int | None]
Record = tuple[
    str,  # id (stable slug)
    str,  # subject
    str,  # dimension
    float,  # value
    str,  # unit
    str,  # tier
    list[Cite],  # citations (Ezekiel chapter, verse_start, verse_end)
    str | None,  # basis
    str | None,  # notes
]

_R = "reed = 6 long cubits (Ezek 40:5)"

TEMPLE_MEASUREMENTS: list[Record] = [
    # ------------------------------------------------------------- datum (40:5)
    (
        "ezt-reed-length",
        "the measuring reed in the man's hand",
        "length",
        6,
        "long-cubit",
        "clear",
        [(40, 5, None)],
        "each cubit being a cubit and a handbreadth (Ezek 40:5)",
        None,
    ),
    (
        "ezt-outer-wall-thickness",
        "thickness of the wall around the outside of the temple area",
        "thickness",
        1,
        "reed",
        "clear",
        [(40, 5, None)],
        _R,
        None,
    ),
    (
        "ezt-outer-wall-height",
        "height of the wall around the outside of the temple area",
        "height",
        1,
        "reed",
        "clear",
        [(40, 5, None)],
        _R,
        None,
    ),
    # ------------------------------------------- the gates (east gate pattern,
    # replicated at the north/south outer gates and the three inner gates)
    (
        "ezt-gate-threshold-depth",
        "threshold of the gate",
        "depth",
        1,
        "reed",
        "clear",
        [(40, 6, None)],
        _R,
        None,
    ),
    (
        "ezt-gate-sideroom-length",
        "side rooms of the gate, length",
        "length",
        1,
        "reed",
        "clear",
        [(40, 7, None)],
        _R,
        None,
    ),
    (
        "ezt-gate-sideroom-breadth",
        "side rooms of the gate, breadth",
        "breadth",
        1,
        "reed",
        "clear",
        [(40, 7, None)],
        _R,
        None,
    ),
    (
        "ezt-gate-sideroom-gap",
        "space between the side rooms",
        "distance",
        5,
        "long-cubit",
        "clear",
        [(40, 7, None)],
        None,
        None,
    ),
    (
        "ezt-gate-inner-threshold-depth",
        "threshold of the gate by the vestibule of the gate at the inner end",
        "depth",
        1,
        "reed",
        "clear",
        [(40, 7, None)],
        _R,
        None,
    ),
    (
        "ezt-gate-vestibule-inside",
        "the vestibule of the gateway, measured on the inside",
        "depth",
        1,
        "reed",
        "fuzzy",
        [(40, 8, None)],
        _R,
        "How 40:8's one-reed inside measure relates to 40:9's eight-cubit "
        "vestibule is a known crux; not used to drive geometry.",
    ),
    (
        "ezt-gate-vestibule-depth",
        "vestibule of the gateway",
        "depth",
        8,
        "long-cubit",
        "clear",
        [(40, 9, None)],
        None,
        None,
    ),
    (
        "ezt-gate-jamb-thickness",
        "jambs of the gate vestibule",
        "thickness",
        2,
        "long-cubit",
        "clear",
        [(40, 9, None)],
        None,
        None,
    ),
    (
        "ezt-gate-siderooms-per-side",
        "side rooms on either side of the gate",
        "count",
        3,
        "item",
        "clear",
        [(40, 10, None), (40, 21, None)],
        None,
        None,
    ),
    (
        "ezt-gate-opening-width",
        "width of the opening of the gateway",
        "breadth",
        10,
        "long-cubit",
        "clear",
        [(40, 11, None)],
        None,
        None,
    ),
    (
        "ezt-gate-opening-length",
        "length of the gateway (at the opening)",
        "length",
        13,
        "long-cubit",
        "fuzzy",
        [(40, 11, None)],
        None,
        "What span the 13 cubits measures (vs the 10-cubit opening width) is "
        "interpretively uncertain; not used to drive geometry.",
    ),
    (
        "ezt-gate-barrier",
        "barrier before the side rooms, on either side",
        "breadth",
        1,
        "long-cubit",
        "clear",
        [(40, 12, None)],
        None,
        None,
    ),
    (
        "ezt-gate-sideroom-side",
        "the side rooms, six cubits on either side",
        "side",
        6,
        "long-cubit",
        "clear",
        [(40, 12, None)],
        None,
        None,
    ),
    (
        "ezt-gate-breadth",
        "breadth of the gate, from the ceiling of one side room to the ceiling of the other",
        "breadth",
        25,
        "long-cubit",
        "clear",
        [
            (40, 13, None),
            (40, 21, None),
            (40, 25, None),
            (40, 29, None),
            (40, 33, None),
            (40, 36, None),
        ],
        None,
        None,
    ),
    (
        "ezt-gate-vestibule-sixty",
        "'he measured also the vestibule, sixty cubits'",
        "length",
        60,
        "long-cubit",
        "fuzzy",
        [(40, 14, None)],
        None,
        "ESV footnote: text uncertain (Hebrew: 'And he made the jambs sixty "
        "cubits, and to the jamb of the court was the gateway all around'). "
        "Not used to drive geometry.",
    ),
    (
        "ezt-gate-length",
        "from the front of the gate at the entrance to the front of the inner "
        "vestibule of the gate",
        "length",
        50,
        "long-cubit",
        "clear",
        [
            (40, 15, None),
            (40, 21, None),
            (40, 25, None),
            (40, 29, None),
            (40, 33, None),
            (40, 36, None),
        ],
        None,
        None,
    ),
    (
        "ezt-outer-gate-steps",
        "steps up to the outer gates",
        "count",
        7,
        "step",
        "clear",
        [(40, 22, None), (40, 26, None)],
        None,
        None,
    ),
    (
        "ezt-inner-gate-steps",
        "steps up to the inner gates",
        "count",
        8,
        "step",
        "clear",
        [(40, 31, None), (40, 34, None), (40, 37, None)],
        None,
        None,
    ),
    (
        "ezt-inner-gate-vestibule-length",
        "vestibules all around (at the inner gates), length",
        "length",
        25,
        "long-cubit",
        "fuzzy",
        [(40, 30, None)],
        None,
        "Ezek 40:30 is text-critically difficult (absent in some witnesses); "
        "ESV prints it. Not used to drive geometry.",
    ),
    (
        "ezt-inner-gate-vestibule-breadth",
        "vestibules all around (at the inner gates), breadth",
        "breadth",
        5,
        "long-cubit",
        "fuzzy",
        [(40, 30, None)],
        None,
        "See ezt-inner-gate-vestibule-length.",
    ),
    # ------------------------------------------------------------------ courts
    (
        "ezt-outer-court-chambers",
        "chambers facing the pavement of the outer court",
        "count",
        30,
        "item",
        "clear",
        [(40, 17, None)],
        None,
        None,
    ),
    (
        "ezt-court-gate-to-gate",
        "from the inner front of the lower (outer) gate to the outer front of the inner court",
        "distance",
        100,
        "long-cubit",
        "clear",
        [(40, 19, None), (40, 23, None), (40, 27, None)],
        None,
        None,
    ),
    (
        "ezt-inner-court-side",
        "the inner court, a square",
        "side",
        100,
        "long-cubit",
        "clear",
        [(40, 47, None)],
        None,
        None,
    ),
    (
        "ezt-slaughter-tables",
        "tables at the north gate on which to slaughter the offerings",
        "count",
        8,
        "item",
        "clear",
        [(40, 41, None)],
        None,
        "Four on either side of the gate (Ezek 40:39-41: two pairs inside the "
        "vestibule, two pairs outside at the entrance).",
    ),
    (
        "ezt-stone-tables-count",
        "tables of hewn stone for the burnt offering",
        "count",
        4,
        "item",
        "clear",
        [(40, 42, None)],
        None,
        None,
    ),
    (
        "ezt-slaughter-hooks-length",
        "hooks fastened all around within",
        "length",
        1,
        "handbreadth",
        "clear",
        [(40, 43, None)],
        None,
        "ESV footnote offers 'shelves' as an alternative for 'hooks'.",
    ),
    (
        "ezt-inner-court-chambers",
        "chambers in the inner court, at the sides of the north and south gates (for the priests)",
        "count",
        2,
        "item",
        "clear",
        [(40, 44, 46)],
        None,
        "ESV follows the Septuagint at 40:44 ('two chambers'; Hebrew 'chambers for singers').",
    ),
    (
        "ezt-stone-table-length",
        "tables of hewn stone for the burnt offering, length",
        "length",
        1.5,
        "long-cubit",
        "clear",
        [(40, 42, None)],
        None,
        None,
    ),
    (
        "ezt-stone-table-breadth",
        "tables of hewn stone for the burnt offering, breadth",
        "breadth",
        1.5,
        "long-cubit",
        "clear",
        [(40, 42, None)],
        None,
        None,
    ),
    (
        "ezt-stone-table-height",
        "tables of hewn stone for the burnt offering, height",
        "height",
        1,
        "long-cubit",
        "clear",
        [(40, 42, None)],
        None,
        None,
    ),
    # ------------------------------------------------- the house: vestibule
    (
        "ezt-house-vestibule-jamb",
        "jambs of the vestibule of the temple, on either side",
        "thickness",
        5,
        "long-cubit",
        "clear",
        [(40, 48, None)],
        None,
        None,
    ),
    (
        "ezt-house-gate-breadth",
        "breadth of the gate of the temple vestibule",
        "breadth",
        14,
        "long-cubit",
        "fuzzy",
        [(40, 48, None)],
        None,
        "ESV follows the Septuagint; the Hebrew lacks 'was fourteen cubits, and "
        "the sidewalls of the gate' (ESV footnote).",
    ),
    (
        "ezt-house-gate-sidewall",
        "sidewalls of the temple vestibule gate, on either side",
        "breadth",
        3,
        "long-cubit",
        "fuzzy",
        [(40, 48, None)],
        None,
        "See ezt-house-gate-breadth (Septuagint reading).",
    ),
    (
        "ezt-house-vestibule-length",
        "length of the temple vestibule",
        "length",
        20,
        "long-cubit",
        "clear",
        [(40, 49, None)],
        None,
        None,
    ),
    (
        "ezt-house-vestibule-breadth",
        "breadth of the temple vestibule",
        "breadth",
        12,
        "long-cubit",
        "fuzzy",
        [(40, 49, None)],
        None,
        "ESV follows the Septuagint ('twelve'); the Hebrew reads 'eleven' (ESV footnote).",
    ),
    (
        "ezt-house-steps",
        "steps up to the temple vestibule",
        "count",
        10,
        "step",
        "fuzzy",
        [(40, 49, None)],
        None,
        "ESV follows the Septuagint ('ten steps'); the Hebrew reads 'by steps "
        "that would go up' without the number (ESV footnote).",
    ),
    (
        "ezt-house-vestibule-pillars",
        "pillars beside the jambs of the temple vestibule, one on either side",
        "count",
        2,
        "item",
        "clear",
        [(40, 49, None)],
        None,
        None,
    ),
    # ------------------------------------------------------ the house: nave
    (
        "ezt-nave-jamb-breadth",
        "jambs of the nave, on each side",
        "breadth",
        6,
        "long-cubit",
        "clear",
        [(41, 1, None)],
        None,
        None,
    ),
    (
        "ezt-nave-entrance-breadth",
        "entrance of the nave",
        "breadth",
        10,
        "long-cubit",
        "clear",
        [(41, 2, None)],
        None,
        None,
    ),
    (
        "ezt-nave-entrance-sidewall",
        "sidewalls of the nave entrance, on either side",
        "breadth",
        5,
        "long-cubit",
        "clear",
        [(41, 2, None)],
        None,
        None,
    ),
    (
        "ezt-nave-length",
        "length of the nave",
        "length",
        40,
        "long-cubit",
        "clear",
        [(41, 2, None)],
        None,
        None,
    ),
    (
        "ezt-nave-breadth",
        "breadth of the nave",
        "breadth",
        20,
        "long-cubit",
        "clear",
        [(41, 2, None)],
        None,
        None,
    ),
    # -------------------------------------------- the house: Most Holy Place
    (
        "ezt-mhp-entrance-jamb",
        "jambs of the entrance to the inner room",
        "thickness",
        2,
        "long-cubit",
        "clear",
        [(41, 3, None)],
        None,
        None,
    ),
    (
        "ezt-mhp-entrance-breadth",
        "entrance of the inner room",
        "breadth",
        6,
        "long-cubit",
        "clear",
        [(41, 3, None)],
        None,
        None,
    ),
    (
        "ezt-mhp-entrance-sidewall",
        "sidewalls of the inner-room entrance",
        "breadth",
        7,
        "long-cubit",
        "fuzzy",
        [(41, 3, None)],
        None,
        "ESV follows the Septuagint ('the sidewalls on either side'); the "
        "Hebrew reads 'and the breadth' (ESV footnote).",
    ),
    (
        "ezt-mhp-length",
        "length of the Most Holy Place",
        "length",
        20,
        "long-cubit",
        "clear",
        [(41, 4, None)],
        None,
        None,
    ),
    (
        "ezt-mhp-breadth",
        "breadth of the Most Holy Place, across the nave",
        "breadth",
        20,
        "long-cubit",
        "clear",
        [(41, 4, None)],
        None,
        None,
    ),
    # ------------------------------------------- the house: walls + chambers
    (
        "ezt-house-wall-thickness",
        "wall of the temple",
        "thickness",
        6,
        "long-cubit",
        "clear",
        [(41, 5, None)],
        None,
        None,
    ),
    (
        "ezt-side-chamber-breadth",
        "side chambers all around the temple",
        "breadth",
        4,
        "long-cubit",
        "clear",
        [(41, 5, None)],
        None,
        None,
    ),
    (
        "ezt-side-chamber-stories",
        "side chambers, stories one over another",
        "count",
        3,
        "story",
        "clear",
        [(41, 6, None)],
        None,
        None,
    ),
    (
        "ezt-side-chambers-per-story",
        "side chambers in each story",
        "count",
        30,
        "item",
        "clear",
        [(41, 6, None)],
        None,
        None,
    ),
    (
        "ezt-house-platform-height",
        "raised platform all around the temple (the foundations of the side chambers)",
        "height",
        1,
        "reed",
        "clear",
        [(41, 8, None)],
        "a full reed of six long cubits (Ezek 41:8)",
        None,
    ),
    (
        "ezt-side-chamber-outer-wall",
        "thickness of the outer wall of the side chambers",
        "thickness",
        5,
        "long-cubit",
        "clear",
        [(41, 9, None)],
        None,
        None,
    ),
    (
        "ezt-chambers-gap",
        "between the side chambers of the temple and the other chambers, all around",
        "distance",
        20,
        "long-cubit",
        "clear",
        [(41, 10, None), (42, 3, None)],
        None,
        None,
    ),
    (
        "ezt-free-space-breadth",
        "breadth of the free space around the house",
        "breadth",
        5,
        "long-cubit",
        "clear",
        [(41, 11, None)],
        None,
        None,
    ),
    # ------------------------------------------------- the western building
    (
        "ezt-west-building-breadth",
        "building facing the separate yard on the west side, breadth",
        "breadth",
        70,
        "long-cubit",
        "clear",
        [(41, 12, None)],
        None,
        None,
    ),
    (
        "ezt-west-building-wall",
        "wall of the western building, all around",
        "thickness",
        5,
        "long-cubit",
        "clear",
        [(41, 12, None)],
        None,
        None,
    ),
    (
        "ezt-west-building-length",
        "building facing the separate yard on the west side, length",
        "length",
        90,
        "long-cubit",
        "clear",
        [(41, 12, None)],
        None,
        None,
    ),
    # ------------------------------------------------------- house envelope
    (
        "ezt-house-length",
        "the temple, length",
        "length",
        100,
        "long-cubit",
        "clear",
        [(41, 13, None)],
        None,
        None,
    ),
    (
        "ezt-yard-building-length",
        "the yard and the building with its walls, length",
        "length",
        100,
        "long-cubit",
        "clear",
        [(41, 13, None)],
        None,
        None,
    ),
    (
        "ezt-house-front-breadth",
        "breadth of the east front of the temple and the yard",
        "breadth",
        100,
        "long-cubit",
        "clear",
        [(41, 14, None)],
        None,
        None,
    ),
    (
        "ezt-west-building-galleries-length",
        "length of the building facing the yard at the back with its galleries",
        "length",
        100,
        "long-cubit",
        "clear",
        [(41, 15, None)],
        None,
        None,
    ),
    # ---------------------------------------------------- wooden altar/table
    (
        "ezt-wood-altar-height",
        "the altar of wood (the table that is before the LORD), height",
        "height",
        3,
        "long-cubit",
        "clear",
        [(41, 22, None)],
        None,
        None,
    ),
    (
        "ezt-wood-altar-length",
        "the altar of wood, length",
        "length",
        2,
        "long-cubit",
        "clear",
        [(41, 22, None)],
        None,
        None,
    ),
    (
        "ezt-wood-altar-breadth",
        "the altar of wood, breadth",
        "breadth",
        2,
        "long-cubit",
        "fuzzy",
        [(41, 22, None)],
        None,
        "ESV follows the Septuagint; the Hebrew lacks 'two cubits broad' (ESV footnote).",
    ),
    # -------------------------------------------------- priests' chambers (42)
    (
        "ezt-priest-chambers-length",
        "the north chamber block opposite the separate yard, length",
        "length",
        100,
        "long-cubit",
        "clear",
        [(42, 2, None), (42, 8, None)],
        None,
        None,
    ),
    (
        "ezt-priest-chambers-breadth",
        "the north chamber block, breadth",
        "breadth",
        50,
        "long-cubit",
        "clear",
        [(42, 2, None)],
        None,
        None,
    ),
    (
        "ezt-priest-chambers-stories",
        "the chamber blocks, stories",
        "count",
        3,
        "story",
        "clear",
        [(42, 3, None), (42, 6, None)],
        None,
        None,
    ),
    (
        "ezt-chambers-passage-width",
        "passage inward before the chambers, width",
        "breadth",
        10,
        "long-cubit",
        "clear",
        [(42, 4, None)],
        None,
        None,
    ),
    (
        "ezt-chambers-passage-length",
        "passage inward before the chambers, length",
        "length",
        100,
        "long-cubit",
        "fuzzy",
        [(42, 4, None)],
        None,
        "ESV follows the Septuagint/Syriac ('a hundred cubits long'); the "
        "Hebrew reads 'a way of one cubit' (ESV footnote).",
    ),
    (
        "ezt-chambers-outer-wall-length",
        "wall outside parallel to the chambers, toward the outer court, length",
        "length",
        50,
        "long-cubit",
        "clear",
        [(42, 7, None), (42, 8, None)],
        None,
        None,
    ),
    # ------------------------------------------------- the precinct (42:15-20)
    (
        "ezt-precinct-side",
        "the temple area measured on each of its four sides, with a wall all "
        "around, to make a separation between the holy and the common",
        "side",
        500,
        "long-cubit",
        "debated",
        [(42, 16, 20)],
        None,
        "ESV prints '500 cubits by the measuring reed'. The Hebrew (and e.g. "
        "NASB) reads 500 REEDS (= 3,000 cubits) - a genuine translation-level "
        "dispute. Rendered per the ESV (500 cubits), which also closes the "
        "chapter's own arithmetic (50+100+50+100+100+100 = 500 east-west); "
        "see RENDERING-DECISIONS entry #7.",
    ),
    # --------------------------------------------------- the altar (43:13-17)
    (
        "ezt-altar-base-height",
        "base of the altar",
        "height",
        1,
        "long-cubit",
        "clear",
        [(43, 13, None)],
        "the cubit being a cubit and a handbreadth (Ezek 43:13)",
        "ESV footnote offers 'its gutter shall be one cubit deep' as an alternative.",
    ),
    (
        "ezt-altar-base-breadth",
        "base of the altar, breadth",
        "breadth",
        1,
        "long-cubit",
        "clear",
        [(43, 13, None)],
        None,
        None,
    ),
    (
        "ezt-altar-base-rim",
        "rim around the edge of the altar base",
        "breadth",
        1,
        "span",
        "clear",
        [(43, 13, None)],
        "a span is about 9 in / 22 cm (ESV note), i.e. roughly 0.43 of the long cubit's ~21 in",
        None,
    ),
    (
        "ezt-altar-lower-ledge-rise",
        "from the base on the ground to the lower ledge",
        "height",
        2,
        "long-cubit",
        "clear",
        [(43, 14, None)],
        None,
        None,
    ),
    (
        "ezt-altar-lower-ledge-breadth",
        "breadth of the lower ledge",
        "breadth",
        1,
        "long-cubit",
        "clear",
        [(43, 14, None)],
        None,
        None,
    ),
    (
        "ezt-altar-upper-ledge-rise",
        "from the smaller ledge to the larger ledge",
        "height",
        4,
        "long-cubit",
        "clear",
        [(43, 14, None)],
        None,
        None,
    ),
    (
        "ezt-altar-upper-ledge-breadth",
        "breadth at the larger ledge step",
        "breadth",
        1,
        "long-cubit",
        "clear",
        [(43, 14, None)],
        None,
        None,
    ),
    (
        "ezt-altar-hearth-height",
        "the altar hearth",
        "height",
        4,
        "long-cubit",
        "clear",
        [(43, 15, None)],
        None,
        "Four horns project upward from the hearth (Ezek 43:15); no horn dimension is given.",
    ),
    (
        "ezt-altar-horns",
        "horns projecting upward from the altar hearth",
        "count",
        4,
        "item",
        "clear",
        [(43, 15, None)],
        None,
        "No horn dimension is given; rendered size is interpretive (RENDERING-DECISIONS entry #7).",
    ),
    (
        "ezt-altar-hearth-side",
        "the altar hearth, square",
        "side",
        12,
        "long-cubit",
        "clear",
        [(43, 16, None)],
        None,
        None,
    ),
    (
        "ezt-altar-ledge-side",
        "the ledge of the altar, square",
        "side",
        14,
        "long-cubit",
        "clear",
        [(43, 17, None)],
        None,
        None,
    ),
    (
        "ezt-altar-ledge-rim",
        "rim around the altar ledge",
        "breadth",
        0.5,
        "long-cubit",
        "clear",
        [(43, 17, None)],
        None,
        None,
    ),
    (
        "ezt-altar-surround-base",
        "the base of the altar, all around",
        "breadth",
        1,
        "long-cubit",
        "clear",
        [(43, 17, None)],
        None,
        "The steps of the altar face east (Ezek 43:17) - orientation, not a "
        "measurement; consumed directly by the renderer.",
    ),
]
